### PR TITLE
Updated Quickstart Table Values + Add Product Change Log

### PR DESCRIPTION
**Pull request by jasSust**
*Removed user guide mentions of scaling

### CODE REVIEW

**Comment by bcwaldon** [comment]
@jasSust Can you also provide the markdown updates in this PR? I only see HTML

**Comment by jasSust** [comment]
*Added updates to quickstart

**Comment by xuberance137** [comment]
Make the table match the following fields from the API

image

**Comment by xuberance137** [comment]
let's have a distinct new column for description and also a have a column listing the `indicator` in addition to the `hazard` so that we are being clear on the fact that each row in the table is an indicator

**Comment by jasSust** [comment]
@bcwaldon pushed additional changes here 

** New Product Updates page
** Quickstart table updates

**Pull request merged**
