### PR TITLE
Publish risk data indicators

### PR DESCRIPTION
**Pull request by bcwaldon**
Screen Shot 2022-01-07 at 11 28 12 AM

### CODE REVIEW

**Comment by bcwaldon** [comment]
Here is a preview

Screen Shot 2022-01-07 at 11 20 46 AM

**Comment by bcwaldon** [comment]
Screen Shot 2022-01-07 at 11 23 14 AM

**Comment by xuberance137** [comment]
@bcwaldon Thanks for putting this together. Two updates: For forward looking table, [1] wildfire row, in the heatmap coding range, it should be modified to be LOW: 0-0.1 MEDIUM: 0.1-1.0 and HIGH: >1.0. [2] The resolution column for wildfire should be 14km (not 100km as listed). I have updated the PDF version accordingly. Once these changes are in place, everything else LTGM. Kindly merge

**Comment by bcwaldon** [comment]
> @bcwaldon Thanks for putting this together. Two updates: For forward looking table, [1] wildfire row, in the heatmap coding range, it should be modified to be LOW: 0-0.1 MEDIUM: 0.1-1.0 and HIGH: >1.0. [2] The resolution column for wildfire should be 14km (not 100km as listed). I have updated the PDF version accordingly. Once these changes are in place, everything else LTGM. Kindly merge

Thanks for the review. Updates will be published shortly.

**Pull request merged**
